twig:
  file_name_pattern: "*.twig"
  form_themes: ["@TalesFromADevFlowbite/form/default.html.twig"]
  globals:
    menu_service: "@App\\Service\\MenuService"

when@test:
  twig:
    strict_variables: true
